### ISSUE TITLE
flutter 3.29 support for the 3.x branch

### ISSUE THREAD

**Issue by valerauko** [ThexXTURBOXx/flutter_web_auth_2#155]
Thanks for maintaining this library!

I noticed that 3.1.2 can't build with flutter 3.29. Android compilation fails with the following errors:
```
e: file:///usr/local/dev/.pub-cache/hosted/pub.dev/flutter_web_auth_2-3.1.2/android/src/main/kotlin/com/linusu/flutter_web_auth_2/FlutterWebAuth2Plugin.kt:22:33 Unresolved reference 'Registrar'.
e: file:///usr/local/dev/.pub-cache/hosted/pub.dev/flutter_web_auth_2-3.1.2/android/src/main/kotlin/com/linusu/flutter_web_auth_2/FlutterWebAuth2Plugin.kt:24:39 Unresolved reference 'messenger'.
e: file:///usr/local/dev/.pub-cache/hosted/pub.dev/flutter_web_auth_2-3.1.2/android/src/main/kotlin/com/linusu/flutter_web_auth_2/FlutterWebAuth2Plugin.kt:24:62 Unresolved reference 'context'.
3 warnings

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_web_auth_2:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```

It seems that the 3.29 release removed imperative plugin registration.
Sadly I can't upgrade to 4.x of the library, because I need to support iOS 15 too.

Could you please backport 0aea29e5c7e03b7a36ce725efe9faf83d4dcadf4 for the 3.x branch too?
